project_id = "weglbznezxxkaxsiifjv"

[functions.subscribe-email]
verify_jwt = false

[functions.validate-access]
verify_jwt = false

[functions.admin-mutate]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false

[functions.telegram-admin]
verify_jwt = false